//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrypTool.Plugins.HillCipherAttack.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrypTool.Plugins.HillCipherAttack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet ähnelt.
        /// </summary>
        internal static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet  ähnelt.
        /// </summary>
        internal static string AlphabetCaption {
            get {
                return ResourceManager.GetString("AlphabetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alphabet - Defintion of allowed characters ähnelt.
        /// </summary>
        internal static string AlphabetTooltip {
            get {
                return ResourceManager.GetString("AlphabetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack Type ähnelt.
        /// </summary>
        internal static string AttackTypeCaption {
            get {
                return ResourceManager.GetString("AttackTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select between Kown Plaintext and Ciphertext Only Attack. ähnelt.
        /// </summary>
        internal static string AttackTypeTooltip {
            get {
                return ResourceManager.GetString("AttackTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cipher Input ähnelt.
        /// </summary>
        internal static string CCaption {
            get {
                return ResourceManager.GetString("CCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cipher ähnelt.
        /// </summary>
        internal static string Cipher {
            get {
                return ResourceManager.GetString("Cipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cipher Text Input ähnelt.
        /// </summary>
        internal static string CTooltip {
            get {
                return ResourceManager.GetString("CTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary  ähnelt.
        /// </summary>
        internal static string DictCaption {
            get {
                return ResourceManager.GetString("DictCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dictionary for Plaintext generation ähnelt.
        /// </summary>
        internal static string DictTooltip {
            get {
                return ResourceManager.GetString("DictTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kown Plaintext/Ciphertext Only Attack for Hill Cipher ähnelt.
        /// </summary>
        internal static string HillCipherAttackCaption {
            get {
                return ResourceManager.GetString("HillCipherAttackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Implements the Kown Plaintext/Ciphertext Only Attack for Hill Cipher ähnelt.
        /// </summary>
        internal static string HillCipherAttackTooltip {
            get {
                return ResourceManager.GetString("HillCipherAttackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The calculated key is incorrect. ähnelt.
        /// </summary>
        internal static string IncorrectKey {
            get {
                return ResourceManager.GetString("IncorrectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a not allowed character in the Input ähnelt.
        /// </summary>
        internal static string InputContainsIllegalCharacter {
            get {
                return ResourceManager.GetString("InputContainsIllegalCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid text matrix ähnelt.
        /// </summary>
        internal static string InvalidException {
            get {
                return ResourceManager.GetString("InvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation Method ähnelt.
        /// </summary>
        internal static string InversCalcTypeCaption {
            get {
                return ResourceManager.GetString("InversCalcTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select between adjoint matrix and eigenvectors to calculate the inverse matrix. ähnelt.
        /// </summary>
        internal static string InverseCalcTypeTooltip {
            get {
                return ResourceManager.GetString("InverseCalcTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string KCaption {
            get {
                return ResourceManager.GetString("KCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keydimension ähnelt.
        /// </summary>
        internal static string KDimCaption {
            get {
                return ResourceManager.GetString("KDimCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Dimension of the key Matrix ähnelt.
        /// </summary>
        internal static string KDimTooltip {
            get {
                return ResourceManager.GetString("KDimTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keydimension ähnelt.
        /// </summary>
        internal static string Keydimension {
            get {
                return ResourceManager.GetString("Keydimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimension ähnelt.
        /// </summary>
        internal static string KeyDimensionHeader {
            get {
                return ResourceManager.GetString("KeyDimensionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string KeyHeader {
            get {
                return ResourceManager.GetString("KeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key: {0} ähnelt.
        /// </summary>
        internal static string KeyValue {
            get {
                return ResourceManager.GetString("KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Matrix ähnelt.
        /// </summary>
        internal static string KMatCaption {
            get {
                return ResourceManager.GetString("KMatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Matrix as numbers ähnelt.
        /// </summary>
        internal static string KMatTooltip {
            get {
                return ResourceManager.GetString("KMatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key Text Output ähnelt.
        /// </summary>
        internal static string KTooltip {
            get {
                return ResourceManager.GetString("KTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string LanguageCaption {
            get {
                return ResourceManager.GetString("LanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select between German and English dictionary entries ähnelt.
        /// </summary>
        internal static string LanguageTooltip {
            get {
                return ResourceManager.GetString("LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modulus ähnelt.
        /// </summary>
        internal static string ModulusCaption {
            get {
                return ResourceManager.GetString("ModulusCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter m - Length of the Alphabet ähnelt.
        /// </summary>
        internal static string ModulusTooltip {
            get {
                return ResourceManager.GetString("ModulusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception: The number of columns of the first matrix must be equal to the number of rows of the second matrix. ähnelt.
        /// </summary>
        internal static string MultiplicationException {
            get {
                return ResourceManager.GetString("MultiplicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No dictionary available ähnelt.
        /// </summary>
        internal static string NoDictionary {
            get {
                return ResourceManager.GetString("NoDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no identity matrix ähnelt.
        /// </summary>
        internal static string NoIdentityMatrix {
            get {
                return ResourceManager.GetString("NoIdentityMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The key cannot be calculated. ähnelt.
        /// </summary>
        internal static string NoKeyFound {
            get {
                return ResourceManager.GetString("NoKeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception: The matrix is not square. ähnelt.
        /// </summary>
        internal static string NoSquareMatrix {
            get {
                return ResourceManager.GetString("NoSquareMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are not enough values for the dimension {0} to execute the calculation. ähnelt.
        /// </summary>
        internal static string NotEnoughData {
            get {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The matrix {0} is not invertable. ähnelt.
        /// </summary>
        internal static string NotInvertable {
            get {
                return ResourceManager.GetString("NotInvertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no valid key in dimension {0} ähnelt.
        /// </summary>
        internal static string NoValidKeyForDim {
            get {
                return ResourceManager.GetString("NoValidKeyForDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext Input ähnelt.
        /// </summary>
        internal static string PCaption {
            get {
                return ResourceManager.GetString("PCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext ähnelt.
        /// </summary>
        internal static string PlainHeader {
            get {
                return ResourceManager.GetString("PlainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plaintext ähnelt.
        /// </summary>
        internal static string Plaintext {
            get {
                return ResourceManager.GetString("Plaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plain Text Input ähnelt.
        /// </summary>
        internal static string PTooltip {
            get {
                return ResourceManager.GetString("PTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        internal static string ScoreHeader {
            get {
                return ResourceManager.GetString("ScoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Key Dimension ähnelt.
        /// </summary>
        internal static string StartKeyDimensionCaption {
            get {
                return ResourceManager.GetString("StartKeyDimensionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Calculation of the key starts at this dimension +1 ähnelt.
        /// </summary>
        internal static string StartKeyDimensionTooltip {
            get {
                return ResourceManager.GetString("StartKeyDimensionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top 25 ähnelt.
        /// </summary>
        internal static string TopRes {
            get {
                return ResourceManager.GetString("TopRes", resourceCulture);
            }
        }
    }
}
